package com.oscaribarra.mealrotator.activities

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.ViewGroup
import android.widget.CheckBox
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.oscaribarra.mealrotator.R
import com.oscaribarra.mealrotator.databinding.ActivityGroceryListBinding

class GroceryListActivity : AppCompatActivity() {

    private lateinit var binding: ActivityGroceryListBinding

    private data class ChecklistItem(
        val label: String,
        var checked: Boolean = false
    )

    private val checklistItems = mutableListOf<ChecklistItem>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityGroceryListBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val text = intent.getStringExtra(EXTRA_GROCERY_TEXT).orEmpty()
        val (mealsText, groceryLines) = parseMealsAndGroceryLines(text)

        binding.tvMealsList.text = mealsText

        checklistItems.clear()
        checklistItems.addAll(groceryLines.map { ChecklistItem(it, checked = false) })

        binding.rvChecklist.layoutManager = LinearLayoutManager(this)
        binding.rvChecklist.adapter = ChecklistAdapter(checklistItems)

        binding.btnCopy.setOnClickListener {
            val export = exportChecklistText(includeCheckedMarks = true, includeMeals = true, mealsText = mealsText)
            val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            clipboard.setPrimaryClip(ClipData.newPlainText("Grocery List", export))
            Toast.makeText(this, "Copied to clipboard", Toast.LENGTH_SHORT).show()
        }

        binding.btnShare.setOnClickListener {
            val export = exportChecklistText(includeCheckedMarks = true, includeMeals = true, mealsText = mealsText)
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "Grocery List")
                putExtra(Intent.EXTRA_TEXT, export)
            }
            startActivity(Intent.createChooser(shareIntent, "Share grocery list"))
        }
    }

    /**
     * Takes the text generated by MainActivity.buildGroceryListText() and splits it into:
     * - mealsText: pretty multi-line list for the top section
     * - groceryLines: each checklist row (no bullets)
     */
    private fun parseMealsAndGroceryLines(fullText: String): Pair<String, List<String>> {
        val lines = fullText.lines()

        var inMeals = false
        var inGrocery = false

        val meals = mutableListOf<String>()
        val groceries = mutableListOf<String>()

        for (raw in lines) {
            val line = raw.trim()
            if (line.isBlank()) continue

            when {
                line.equals("Meals this week:", ignoreCase = true) -> {
                    inMeals = true
                    inGrocery = false
                    continue
                }
                line.equals("Grocery List:", ignoreCase = true) -> {
                    inMeals = false
                    inGrocery = true
                    continue
                }
            }

            if (inMeals) {
                meals.add(stripBullet(line))
            } else if (inGrocery) {
                groceries.add(stripBullet(line))
            }
        }

        val mealsText = if (meals.isEmpty()) {
            "No meals found"
        } else {
            meals.joinToString(separator = "\n") { "• $it" }
        }

        return mealsText to groceries
    }

    private fun stripBullet(s: String): String {
        return s.removePrefix("•").trim()
    }

    private fun exportChecklistText(
        includeCheckedMarks: Boolean,
        includeMeals: Boolean,
        mealsText: String
    ): String {
        val sb = StringBuilder()

        if (includeMeals) {
            sb.append("Meals this week:\n")
            sb.append(mealsText.trim())
            sb.append("\n\n")
        }

        sb.append("Grocery checklist:\n")
        checklistItems.forEach { item ->
            val mark = if (!includeCheckedMarks) "" else if (item.checked) "[x] " else "[ ] "
            sb.append(mark).append(item.label).append('\n')
        }

        return sb.toString().trim()
    }

    private class ChecklistAdapter(
        private val items: List<ChecklistItem>
    ) : RecyclerView.Adapter<ChecklistAdapter.VH>() {

        class VH(val checkBox: CheckBox) : RecyclerView.ViewHolder(checkBox)

        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH {
            val checkBox = LayoutInflater.from(parent.context)
                .inflate(R.layout.item_grocery_check, parent, false) as CheckBox
            return VH(checkBox)
        }

        override fun onBindViewHolder(holder: VH, position: Int) {
            val item = items[position]

            // Prevent recycling issues by clearing listener first
            holder.checkBox.setOnCheckedChangeListener(null)

            holder.checkBox.text = item.label
            holder.checkBox.isChecked = item.checked

            holder.checkBox.setOnCheckedChangeListener { _, isChecked ->
                item.checked = isChecked
            }
        }

        override fun getItemCount(): Int = items.size
    }

    companion object {
        const val EXTRA_GROCERY_TEXT = "EXTRA_GROCERY_TEXT"
    }
}
