package com.oscaribarra.ibarramealprep

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

// Represents the UI state for the Add/Edit Meal screen
data class AddMealUiState(
    val mealName: String = "",
    val ingredients: String = "",
    val instructions: String = "",
    val cookTime: String = "",
    val isSaving: Boolean = false,
    val saveSuccess: Boolean = false, // To signal navigation or UI update after successful save
    val isLoadingExistingMeal: Boolean = false, // To show loading when fetching an existing meal
    val errorMessage: String? = null,
    val currentMealId: Int? = null, // To know if we are editing an existing meal
    val isEditMode: Boolean = false // Derived from currentMealId != null
)

class AddMealViewModel(
    private val mealRepository: MealRepository,
    private val existingMealId: Int? // Injected when creating the ViewModel
) : ViewModel() {

    private val _uiState = MutableStateFlow(AddMealUiState(currentMealId = existingMealId, isEditMode = existingMealId != null))
    val uiState: StateFlow<AddMealUiState> = _uiState.asStateFlow()

    init {
        if (existingMealId != null) {
            loadMealDetails(existingMealId)
        }
    }

    private fun loadMealDetails(mealId: Int) {
        _uiState.value = _uiState.value.copy(isLoadingExistingMeal = true)
        viewModelScope.launch {
            val meal = mealRepository.getMealById(mealId)
            meal?.let {
                _uiState.value = _uiState.value.copy(
                    mealName = it.name,
                    ingredients = it.ingredients,
                    instructions = it.instructions,
                    cookTime = it.cookTime,
                    isLoadingExistingMeal = false
                )
            } ?: run {
                // Handle case where mealId is provided but meal not found
                _uiState.value = _uiState.value.copy(
                    isLoadingExistingMeal = false,
                    errorMessage = "Meal not found."
                )
            }
        }
    }

    fun updateMealName(name: String) {
        _uiState.value = _uiState.value.copy(mealName = name, errorMessage = null)
    }

    fun updateIngredients(ingredients: String) {
        _uiState.value = _uiState.value.copy(ingredients = ingredients, errorMessage = null)
    }

    fun updateInstructions(instructions: String) {
        _uiState.value = _uiState.value.copy(instructions = instructions, errorMessage = null)
    }

    fun updateCookTime(cookTime: String) {
        _uiState.value = _uiState.value.copy(cookTime = cookTime, errorMessage = null)
    }

    fun saveMeal() {
        val currentName = _uiState.value.mealName.trim()
        if (currentName.isBlank()) {
            _uiState.value = _uiState.value.copy(errorMessage = "Meal name cannot be empty.")
            return
        }
        // Add more validation as needed for other fields

        _uiState.value = _uiState.value.copy(isSaving = true, errorMessage = null)

        viewModelScope.launch {
            try {
                val mealToSave: Meal
                if (_uiState.value.isEditMode && _uiState.value.currentMealId != null) {
                    // Editing an existing meal: Fetch it first to preserve uneditable fields
                    // or fields not directly on the form like isPinnedForNextWeek, lastScheduledDate
                    val existingMeal = mealRepository.getMealById(_uiState.value.currentMealId!!)
                    if (existingMeal != null) {
                        mealToSave = existingMeal.copy(
                            name = currentName,
                            ingredients = _uiState.value.ingredients.trim(),
                            instructions = _uiState.value.instructions.trim(),
                            cookTime = _uiState.value.cookTime.trim()
                        )
                        mealRepository.update(mealToSave)
                    } else {
                        // Should not happen if loadMealDetails was successful, but handle defensively
                        _uiState.value = _uiState.value.copy(isSaving = false, errorMessage = "Error: Original meal not found for update.")
                        return@launch
                    }
                } else {
                    // Adding a new meal
                    mealToSave = Meal(
                        // id will be auto-generated by Room (when id=0)
                        name = currentName,
                        ingredients = _uiState.value.ingredients.trim(),
                        instructions = _uiState.value.instructions.trim(),
                        cookTime = _uiState.value.cookTime.trim()
                        // isPinnedForNextWeek and lastScheduledDate will use defaults (false, null)
                    )
                    mealRepository.insert(mealToSave)
                }
                _uiState.value = _uiState.value.copy(isSaving = false, saveSuccess = true)
            } catch (e: Exception) {
                _uiState.value = _uiState.value.copy(isSaving = false, errorMessage = "Error saving meal: ${e.localizedMessage}")
            }
        }
    }

    // Call this from the UI after observing saveSuccess = true to reset the state
    // (e.g., after navigating away)
    fun onSaveHandled() {
        _uiState.value = _uiState.value.copy(saveSuccess = false, errorMessage = null)
    }

    // Call this if the user navigates away or cancels to clear any transient error messages
    fun onDismissError() {
        _uiState.value = _uiState.value.copy(errorMessage = null)
    }
}